[package]
name = "dogd"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
libdogd = { path = "../libdogd", default-features = false }
multiqueue = "0.3.2"
