[package]
name = "libdogd"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
colored = "2.0.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"

[features]
default = ["stdout"]
stdout = []
